/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';
import SmsCreate from '../model/SmsCreate';
import SmsResponse from '../model/SmsResponse';

/**
* SMS service.
* @module api/SMSApi
* @version 1.0.0
*/
export default class SMSApi {

    /**
    * Constructs a new SMSApi. 
    * @alias module:api/SMSApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getInboxSmsInboxGet operation.
     * @callback module:api/SMSApi~getInboxSmsInboxGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SmsResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lister tous les SMS reçus
     * Récupère tous les SMS reçus.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit] Nombre maximum de SMS à retourner
     * @param {module:api/SMSApi~getInboxSmsInboxGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SmsResponse>}
     */
    getInboxSmsInboxGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SmsResponse];
      return this.apiClient.callApi(
        '/sms/inbox', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLogsLogsGet operation.
     * @callback module:api/SMSApi~getLogsLogsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<{String: Object}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Voir les logs des SMS
     * Récupère l'historique et le statut de tous les SMS envoyés.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit] Nombre maximum de logs à retourner
     * @param {String} [level] Filtre par niveau de log (INFO, WARNING, ERROR, etc.)
     * @param {String} [component] Filtre par composant
     * @param {module:api/SMSApi~getLogsLogsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<{String: Object}>}
     */
    getLogsLogsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'level': opts['level'],
        'component': opts['component']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [{'String': Object}];
      return this.apiClient.callApi(
        '/logs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSentMessagesSmsSentGet operation.
     * @callback module:api/SMSApi~getSentMessagesSmsSentGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SmsResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lister tous les SMS envoyés
     * Récupère tous les SMS envoyés par l'utilisateur actuel.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit] Nombre maximum de SMS à retourner
     * @param {module:api/SMSApi~getSentMessagesSmsSentGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SmsResponse>}
     */
    getSentMessagesSmsSentGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SmsResponse];
      return this.apiClient.callApi(
        '/sms/sent', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the sendSmsSmsPost operation.
     * @callback module:api/SMSApi~sendSmsSmsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SmsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Envoyer un SMS
     * Envoie un SMS au numéro spécifié.  - **phone_number**: Numéro complet avec indicatif international - **message**: Contenu du SMS à envoyer
     * @param {module:model/SmsCreate} smsCreate 
     * @param {module:api/SMSApi~sendSmsSmsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SmsResponse}
     */
    sendSmsSmsPost(smsCreate, callback) {
      let postBody = smsCreate;
      // verify the required parameter 'smsCreate' is set
      if (smsCreate === undefined || smsCreate === null) {
        throw new Error("Missing the required parameter 'smsCreate' when calling sendSmsSmsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SmsResponse;
      return this.apiClient.callApi(
        '/sms', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the simulateReceivedSmsSmsSimulateReceivePost operation.
     * @callback module:api/SMSApi~simulateReceivedSmsSmsSimulateReceivePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SmsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Simulate Received Sms
     * Simule la réception d'un SMS (uniquement pour les tests/développement).
     * @param {String} phoneNumber Numéro de téléphone de l'expéditeur
     * @param {String} message Contenu du message reçu
     * @param {module:api/SMSApi~simulateReceivedSmsSmsSimulateReceivePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SmsResponse}
     */
    simulateReceivedSmsSmsSimulateReceivePost(phoneNumber, message, callback) {
      let postBody = null;
      // verify the required parameter 'phoneNumber' is set
      if (phoneNumber === undefined || phoneNumber === null) {
        throw new Error("Missing the required parameter 'phoneNumber' when calling simulateReceivedSmsSmsSimulateReceivePost");
      }
      // verify the required parameter 'message' is set
      if (message === undefined || message === null) {
        throw new Error("Missing the required parameter 'message' when calling simulateReceivedSmsSmsSimulateReceivePost");
      }

      let pathParams = {
      };
      let queryParams = {
        'phone_number': phoneNumber,
        'message': message
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SmsResponse;
      return this.apiClient.callApi(
        '/sms/simulate-receive', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
