# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sms_create import SmsCreate

class TestSmsCreate(unittest.TestCase):
    """SmsCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmsCreate:
        """Test SmsCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmsCreate`
        """
        model = SmsCreate()
        if include_optional:
            return SmsCreate(
                phone_number = '',
                message = ''
            )
        else:
            return SmsCreate(
                phone_number = '',
                message = '',
        )
        """

    def testSmsCreate(self):
        """Test SmsCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
