# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sms_api import SMSApi


class TestSMSApi(unittest.TestCase):
    """SMSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SMSApi()

    def tearDown(self) -> None:
        pass

    def test_get_inbox_sms_inbox_get(self) -> None:
        """Test case for get_inbox_sms_inbox_get

        Lister tous les SMS reçus
        """
        pass

    def test_get_logs_logs_get(self) -> None:
        """Test case for get_logs_logs_get

        Voir les logs des SMS
        """
        pass

    def test_get_sent_messages_sms_sent_get(self) -> None:
        """Test case for get_sent_messages_sms_sent_get

        Lister tous les SMS envoyés
        """
        pass

    def test_send_sms_sms_post(self) -> None:
        """Test case for send_sms_sms_post

        Envoyer un SMS
        """
        pass

    def test_simulate_received_sms_sms_simulate_receive_post(self) -> None:
        """Test case for simulate_received_sms_sms_simulate_receive_post

        Simulate Received Sms
        """
        pass


if __name__ == '__main__':
    unittest.main()
