# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sms_status import SmsStatus

class TestSmsStatus(unittest.TestCase):
    """SmsStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmsStatus(self):
        """Test SmsStatus"""
        # inst = SmsStatus()

if __name__ == '__main__':
    unittest.main()
