# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sms_response import SmsResponse

class TestSmsResponse(unittest.TestCase):
    """SmsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmsResponse:
        """Test SmsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmsResponse`
        """
        model = SmsResponse()
        if include_optional:
            return SmsResponse(
                phone_number = '',
                message = '',
                id = '',
                status = 'pending',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error_message = '',
                user_id = ''
            )
        else:
            return SmsResponse(
                phone_number = '',
                message = '',
                id = '',
        )
        """

    def testSmsResponse(self):
        """Test SmsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
