# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_list_messages_admin_messages_get(self) -> None:
        """Test case for list_messages_admin_messages_get

        List Messages
        """
        pass

    def test_list_users_admin_users_get(self) -> None:
        """Test case for list_users_admin_users_get

        List Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
