# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_check_db_structure_debug_db_structure_get(self) -> None:
        """Test case for check_db_structure_debug_db_structure_get

        Check Db Structure
        """
        pass

    def test_debug_mqtt_storage_debug_mqtt_storage_get(self) -> None:
        """Test case for debug_mqtt_storage_debug_mqtt_storage_get

        Debug Mqtt Storage
        """
        pass

    def test_debug_services_debug_services_get(self) -> None:
        """Test case for debug_services_debug_services_get

        Debug Services
        """
        pass

    def test_get_all_messages_debug_all_messages_get(self) -> None:
        """Test case for get_all_messages_debug_all_messages_get

        Get All Messages
        """
        pass

    def test_mqtt_status_debug_mqtt_status_get(self) -> None:
        """Test case for mqtt_status_debug_mqtt_status_get

        Mqtt Status
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
