# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_login_auth_login_post(self) -> None:
        """Test case for login_auth_login_post

        Login
        """
        pass

    def test_register_auth_register_post(self) -> None:
        """Test case for register_auth_register_post

        Register
        """
        pass


if __name__ == '__main__':
    unittest.main()
