/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import HTTPValidationError from './model/HTTPValidationError';
import SmsCreate from './model/SmsCreate';
import SmsResponse from './model/SmsResponse';
import SmsStatus from './model/SmsStatus';
import UserCreate from './model/UserCreate';
import UserResponse from './model/UserResponse';
import ValidationError from './model/ValidationError';
import ValidationErrorLocInner from './model/ValidationErrorLocInner';
import AdminApi from './api/AdminApi';
import AuthenticationApi from './api/AuthenticationApi';
import DefaultApi from './api/DefaultApi';
import SMSApi from './api/SMSApi';


/**
* API for sending and receiving SMS through a GSM module.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SmsGatewayApi = require('index'); // See note below*.
* var xxxSvc = new SmsGatewayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SmsGatewayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SmsGatewayApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SmsGatewayApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The SmsCreate model constructor.
     * @property {module:model/SmsCreate}
     */
    SmsCreate,

    /**
     * The SmsResponse model constructor.
     * @property {module:model/SmsResponse}
     */
    SmsResponse,

    /**
     * The SmsStatus model constructor.
     * @property {module:model/SmsStatus}
     */
    SmsStatus,

    /**
     * The UserCreate model constructor.
     * @property {module:model/UserCreate}
     */
    UserCreate,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
     * The ValidationErrorLocInner model constructor.
     * @property {module:model/ValidationErrorLocInner}
     */
    ValidationErrorLocInner,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The SMSApi service constructor.
    * @property {module:api/SMSApi}
    */
    SMSApi
};
