/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', 'sinon', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('sinon'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.sinon, root.SmsGatewayApi);
  }
}(this, function(expect, sinon, SmsGatewayApi) {
  'use strict';

  var instance;
  var sandbox;

  beforeEach(function() {
    sandbox = sinon.createSandbox();
    instance = new SmsGatewayApi.AdminApi();
  });

  afterEach(function() {
    sandbox.restore();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminApi', function() {
    describe('listMessagesAdminMessagesGet', function() {
      it('should call listMessagesAdminMessagesGet successfully', function(done) {
        var callApiStub = sandbox.stub(instance.apiClient, 'callApi').returns(Promise.resolve([{id: '1', message: 'Test message'}]));
        
        instance.listMessagesAdminMessagesGet(function(error, data, response) {
          expect(error).to.be(null);
          expect(data).to.eql([{id: '1', message: 'Test message'}]);
          expect(callApiStub.calledOnce).to.be(true);
          
          var args = callApiStub.getCall(0).args;
          expect(args[0]).to.be('/admin/messages');
          expect(args[1]).to.be('GET');
          expect(args[7]).to.eql(['APIKeyHeader']); // authNames
          done();
        });
      });
      
      it('should handle errors from listMessagesAdminMessagesGet', function(done) {
        var error = new Error('API Error');
        sandbox.stub(instance.apiClient, 'callApi').rejects(error);
        
        instance.listMessagesAdminMessagesGet(function(err, data, response) {
          expect(err).to.be(error);
          expect(data).to.be(undefined);
          done();
        });
      });
    });

    describe('listUsersAdminUsersGet', function() {
      it('should call listUsersAdminUsersGet successfully', function(done) {
        var mockUsers = [{id: '1', username: 'admin'}, {id: '2', username: 'user'}];
        var callApiStub = sandbox.stub(instance.apiClient, 'callApi').returns(Promise.resolve(mockUsers));
        
        instance.listUsersAdminUsersGet(function(error, data, response) {
          expect(error).to.be(null);
          expect(data).to.eql(mockUsers);
          expect(callApiStub.calledOnce).to.be(true);
          
          var args = callApiStub.getCall(0).args;
          expect(args[0]).to.be('/admin/users');
          expect(args[1]).to.be('GET');
          expect(args[7]).to.eql(['APIKeyHeader']); // authNames
          done();
        });
      });
      
      it('should handle errors from listUsersAdminUsersGet', function(done) {
        var error = new Error('API Error');
        sandbox.stub(instance.apiClient, 'callApi').rejects(error);
        
        instance.listUsersAdminUsersGet(function(err, data, response) {
          expect(err).to.be(error);
          expect(data).to.be(undefined);
          done();
        });
      });
    });
  });
}));
