/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmsGatewayApi);
  }
}(this, function(expect, SmsGatewayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmsGatewayApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('checkDbStructureDebugDbStructureGet', function() {
      it('should call checkDbStructureDebugDbStructureGet successfully', function(done) {
        //uncomment below and update the code to test checkDbStructureDebugDbStructureGet
        //instance.checkDbStructureDebugDbStructureGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('debugMqttStorageDebugMqttStorageGet', function() {
      it('should call debugMqttStorageDebugMqttStorageGet successfully', function(done) {
        //uncomment below and update the code to test debugMqttStorageDebugMqttStorageGet
        //instance.debugMqttStorageDebugMqttStorageGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('debugServicesDebugServicesGet', function() {
      it('should call debugServicesDebugServicesGet successfully', function(done) {
        //uncomment below and update the code to test debugServicesDebugServicesGet
        //instance.debugServicesDebugServicesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllMessagesDebugAllMessagesGet', function() {
      it('should call getAllMessagesDebugAllMessagesGet successfully', function(done) {
        //uncomment below and update the code to test getAllMessagesDebugAllMessagesGet
        //instance.getAllMessagesDebugAllMessagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mqttStatusDebugMqttStatusGet', function() {
      it('should call mqttStatusDebugMqttStatusGet successfully', function(done) {
        //uncomment below and update the code to test mqttStatusDebugMqttStatusGet
        //instance.mqttStatusDebugMqttStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rootGet', function() {
      it('should call rootGet successfully', function(done) {
        //uncomment below and update the code to test rootGet
        //instance.rootGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
