/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmsGatewayApi);
  }
}(this, function(expect, SmsGatewayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmsGatewayApi.SMSApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SMSApi', function() {
    describe('getInboxSmsInboxGet', function() {
      it('should call getInboxSmsInboxGet successfully', function(done) {
        //uncomment below and update the code to test getInboxSmsInboxGet
        //instance.getInboxSmsInboxGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLogsLogsGet', function() {
      it('should call getLogsLogsGet successfully', function(done) {
        //uncomment below and update the code to test getLogsLogsGet
        //instance.getLogsLogsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSentMessagesSmsSentGet', function() {
      it('should call getSentMessagesSmsSentGet successfully', function(done) {
        //uncomment below and update the code to test getSentMessagesSmsSentGet
        //instance.getSentMessagesSmsSentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendSmsSmsPost', function() {
      it('should call sendSmsSmsPost successfully', function(done) {
        //uncomment below and update the code to test sendSmsSmsPost
        //instance.sendSmsSmsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('simulateReceivedSmsSmsSimulateReceivePost', function() {
      it('should call simulateReceivedSmsSmsSimulateReceivePost successfully', function(done) {
        //uncomment below and update the code to test simulateReceivedSmsSmsSimulateReceivePost
        //instance.simulateReceivedSmsSmsSimulateReceivePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
