/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SmsCreate model module.
 * @module model/SmsCreate
 * @version 1.0.0
 */
class SmsCreate {
    /**
     * Constructs a new <code>SmsCreate</code>.
     * @alias module:model/SmsCreate
     * @param phoneNumber {String} Le numéro de téléphone complet avec indicatif
     * @param message {String} Le contenu du message SMS
     */
    constructor(phoneNumber, message) { 
        
        SmsCreate.initialize(this, phoneNumber, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phoneNumber, message) { 
        obj['phone_number'] = phoneNumber;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>SmsCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SmsCreate} obj Optional instance to populate.
     * @return {module:model/SmsCreate} The populated <code>SmsCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmsCreate();

            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SmsCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SmsCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SmsCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['phone_number'] && !(typeof data['phone_number'] === 'string' || data['phone_number'] instanceof String)) {
            throw new Error("Expected the field `phone_number` to be a primitive type in the JSON string but got " + data['phone_number']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

SmsCreate.RequiredProperties = ["phone_number", "message"];

/**
 * Le numéro de téléphone complet avec indicatif
 * @member {String} phone_number
 */
SmsCreate.prototype['phone_number'] = undefined;

/**
 * Le contenu du message SMS
 * @member {String} message
 */
SmsCreate.prototype['message'] = undefined;






export default SmsCreate;

