/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SmsStatus from './SmsStatus';

/**
 * The SmsResponse model module.
 * @module model/SmsResponse
 * @version 1.0.0
 */
class SmsResponse {
    /**
     * Constructs a new <code>SmsResponse</code>.
     * @alias module:model/SmsResponse
     * @param phoneNumber {String} Le numéro de téléphone complet avec indicatif
     * @param message {String} Le contenu du message SMS
     * @param id {String} 
     */
    constructor(phoneNumber, message, id) { 
        
        SmsResponse.initialize(this, phoneNumber, message, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phoneNumber, message, id) { 
        obj['phone_number'] = phoneNumber;
        obj['message'] = message;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>SmsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SmsResponse} obj Optional instance to populate.
     * @return {module:model/SmsResponse} The populated <code>SmsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmsResponse();

            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SmsStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('error_message')) {
                obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SmsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SmsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SmsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['phone_number'] && !(typeof data['phone_number'] === 'string' || data['phone_number'] instanceof String)) {
            throw new Error("Expected the field `phone_number` to be a primitive type in the JSON string but got " + data['phone_number']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['error_message'] && !(typeof data['error_message'] === 'string' || data['error_message'] instanceof String)) {
            throw new Error("Expected the field `error_message` to be a primitive type in the JSON string but got " + data['error_message']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }

        return true;
    }


}

SmsResponse.RequiredProperties = ["phone_number", "message", "id"];

/**
 * Le numéro de téléphone complet avec indicatif
 * @member {String} phone_number
 */
SmsResponse.prototype['phone_number'] = undefined;

/**
 * Le contenu du message SMS
 * @member {String} message
 */
SmsResponse.prototype['message'] = undefined;

/**
 * @member {String} id
 */
SmsResponse.prototype['id'] = undefined;

/**
 * @member {module:model/SmsStatus} status
 */
SmsResponse.prototype['status'] = undefined;

/**
 * @member {Date} created_at
 */
SmsResponse.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
SmsResponse.prototype['updated_at'] = undefined;

/**
 * @member {String} error_message
 */
SmsResponse.prototype['error_message'] = undefined;

/**
 * @member {String} user_id
 */
SmsResponse.prototype['user_id'] = undefined;






export default SmsResponse;

