/**
 * SMS Gateway API
 * API for sending and receiving SMS through a GSM module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SmsStatus.
* @enum {}
* @readonly
*/
export default class SmsStatus {
    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "sent"
         * @const
         */
        "sent" = "sent";

    
        /**
         * value: "failed"
         * @const
         */
        "failed" = "failed";

    
        /**
         * value: "received"
         * @const
         */
        "received" = "received";

    

    /**
    * Returns a <code>SmsStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SmsStatus} The enum <code>SmsStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

