# coding: utf-8

# flake8: noqa
"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.sms_create import SmsCreate
from openapi_client.models.sms_response import SmsResponse
from openapi_client.models.sms_status import SmsStatus
from openapi_client.models.user_create import UserCreate
from openapi_client.models.user_response import UserResponse
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner
