# coding: utf-8

"""
    SMS Gateway API

    API for sending and receiving SMS through a GSM module

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SmsStatus(str, Enum):
    """
    SmsStatus
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    SENT = 'sent'
    FAILED = 'failed'
    RECEIVED = 'received'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SmsStatus from a JSON string"""
        return cls(json.loads(json_str))


